- name: Cambiar IP a una MV en Proxmox
  hosts: localhost
  tasks:
    - name: Cambiar IP a MV
      community.general.proxmox_kvm:
        api_host: 192.168.0.10:8006
        api_user: root@pam
        api_password: 206xs75
        validate_certs: false
        node: proxmox2               # Nodo donde reside la plantilla
        vmid: 114        # ID de la VM clonada
        name: server114  # Nombre final basado en VMID
        net:
          net0: 'virtio,bridge=vmbr0'  # Interfaz de red en modo bridge
        ipconfig:
          ipconfig0: 'ip=192.168.0.114/24' # IP basada en el VMID        
        nameservers:                   # Servidores DNS
          - 8.8.8.8
          - 8.8.4.4            
        update: true
        update_unsafe: true                   # Actualizar la configuración
        state: present
      register: update_result

    - name: Mostrar resultados del clon, renombrado y encendido
      debug:
        msg:
          "{{ update_result }}"

    - name: Mostrar info de la red
      community.general.proxmox_vm_info:
        api_host: 192.168.0.10:8006
        api_user: root@pam
        api_password: 206xs75
        validate_certs: false
        node: proxmox2               # Nodo donde reside la plantilla
        vmid: 114        # ID de la VM clonada
        network: true
        
