---
- name: Test connection to ServiceNow
  hosts: localhost
  gather_facts: false
  vars:
    servicenow_instance: "https://dev262465.service-now.com"

  tasks:
    - name: Check ServiceNow connection
      ansible.builtin.uri:
        url: "{{ servicenow_instance }}/api/now/table/incident"
        method: GET
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        force_basic_auth: true
        status_code: 200
        validate_certs: false
      register: servicenow_response

    - name: Show response
      ansible.builtin.debug:
        var: servicenow_response
