- name: Probar API de Proxmox con módulo uri y token
  hosts: localhost
  tasks:
    - name: Listar nodos en Proxmox
      ansible.builtin.uri:
        url: "https://192.168.0.10:8006/api2/json/nodes"
        method: GET
        headers:
          Authorization: "PVEAPIToken=AAP@pam!AAPtoken=b66cf0fd-83ce-450f-b2a2-52aa6a808c53"
        validate_certs: false
      register: result

    - name: Mostrar resultados
      ansible.builtin.debug:
        var: result.json
