- name: Probar API de Proxmox con módulo uri
  hosts: localhost
  tasks:
    - name: Listar nodos en Proxmox
      uri:
        url: "https://192.168.0.10:8006/api2/json/nodes"
        method: GET
        user: "root@pam"
        password: "206xs75"
        validate_certs: false
      register: result

    - name: Mostrar resultados
      debug:
        var: result.json
