- name: Registrar host en la CMDB de ServiceNow
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Registrar el servidor en la CMDB
      servicenow.itsm.configuration_item:
        instance:
          host: https://dev262465.service-now.com # Instancia
          username: "{{ ansible_user }}"          # Usuario de ServiceNow
          password: "{{ ansible_password }}"      # Contraseña de ServiceNow
        category: Hardware
        environment: production
        sys_class_name: cmdb_ci_server     # Clase del CI
        name: "{{ server_name }}"            # Nombre del servidor
        ip_address: "{{ server_ip }}"        # Dirección IP
        operational_status: 1              # Estado "Activo"
        other:
          discovery_source: AAP Automation   # Fuente de descubrimiento
          ram: "{{ server_memory }}"           # Memoria RAM
          disk_space: "{{ server_disk }}"      # Espacio en disco
          os: "{{ server_os }}"                # Sistema Operativo
          owned_by: "{{ requester_user }}"     # Usuario propietario
          managed_by: "{{ requester_user }}"   # Usuario responsable
          virtual: true                        # Especificar que es una máquina virtual
      register: cmdb_response

    - name: Verificar la respuesta del registro en CMDB
      ansible.builtin.debug:
        msg: "Registro en la CMDB completado con éxito: {{ cmdb_response }}"
