---
- name: Compliance Check for Linux Servers
  hosts: all
  gather_facts: true
  vars:
    non_compliant_servers: []

  tasks:
    - name: Ensure firewall is installed
      ansible.builtin.dnf:
        name: firewalld
        state: present
      register: firewall_install_result
      ignore_errors: true

    - name: Ensure firewall is active
      ansible.builtin.systemd:
        name: firewalld
        state: started
        enabled: true
      register: firewall_status_result
      ignore_errors: true

    - name: Ensure rkhunter is installed
      ansible.builtin.dnf:
        name: rkhunter
        state: present
      register: rkhunter_install_result
      ignore_errors: true

    - name: Evaluate server compliance
      ansible.builtin.set_fact:
        compliance_details:
          hostname: "{{ inventory_hostname }}"
          firewall_installed: "{{ not firewall_install_result is failed }}"
          firewall_active: "{{ not firewall_status_result is failed }}"
          rkhunter_installed: "{{ not rkhunter_install_result is failed }}"
          compliant: >-
            {{
              not firewall_install_result is failed and
              not firewall_status_result is failed and
              not rkhunter_install_result is failed
            }}

    - name: Add non-compliant servers to temporary list
      ansible.builtin.set_fact:
        non_compliant_servers: "{{ non_compliant_servers + [compliance_details] }}"
      when: not compliance_details.compliant

- name: Consolidate and fail if necessary
  hosts: localhost
  tasks:
    - name: Combine non-compliant server lists from all hosts
      ansible.builtin.set_fact:
        all_non_compliant_servers: "{{ groups['all'] | map('extract', hostvars, 'non_compliant_servers') | flatten }}"

    - name: Debug consolidated non-compliant servers
      ansible.builtin.debug:
        var: all_non_compliant_servers

    - name: Fail if there are non-compliant servers
      ansible.builtin.fail:
        msg: >
          Compliance check failed. Non-compliant servers:
          {{ all_non_compliant_servers | to_nice_json }}
      when: all_non_compliant_servers | length > 0
