---
- name: Compliance Check for Linux Servers
  hosts: all
  gather_facts: true
  tasks:
    # Verificar que el firewall esté instalado
    - name: Ensure firewall is installed
      ansible.builtin.dnf:
        name: firewalld
        state: present
      register: firewall_install_result

    # Verificar que el firewall esté activo
    - name: Ensure firewall is active
      ansible.builtin.systemd:
        name: firewalld
        state: started
        enabled: true
      register: firewall_status_result

    # Verificar que rkhunter esté instalado
    - name: Ensure rkhunter is installed
      ansible.builtin.dnf:
        name: rkhunter
        state: present
      register: rkhunter_install_result

    # Evaluar compliance del servidor
    - name: Fail if the server is not compliant
      ansible.builtin.fail:
        msg: >
          Server {{ inventory_hostname }} is not compliant:
          - Firewall installed: {{ firewall_install_result is succeeded }}
          - Firewall active: {{ firewall_status_result is succeeded }}
          - rkhunter installed: {{ rkhunter_install_result is succeeded }}
      when: >
        not (
          firewall_install_result is succeeded and
          firewall_status_result is succeeded and
          rkhunter_install_result is succeeded
        )

    # Depurar estado de compliance (opcional)
    - name: Debug server compliance status
      ansible.builtin.debug:
        msg: >
          Server {{ inventory_hostname }} is compliant:
          - Firewall installed: {{ firewall_install_result is succeeded }}
          - Firewall active: {{ firewall_status_result is succeeded }}
          - rkhunter installed: {{ rkhunter_install_result is succeeded }}
      when: >
        firewall_install_result is succeeded and
        firewall_status_result is succeeded and
        rkhunter_install_result is succeeded
