---
- name: Compliance Check for Linux Servers
  hosts: all
  gather_facts: true
  vars:
    non_compliant_servers: []

  tasks:
    # Verificar que el firewall esté instalado
    - name: Ensure firewall is installed
      ansible.builtin.dnf:
        name: firewalld
        state: present
      register: firewall_install_result
      ignore_errors: true

    # Verificar que el firewall esté activo
    - name: Ensure firewall is active
      ansible.builtin.systemd:
        name: firewalld
        state: started
        enabled: true
      register: firewall_status_result
      ignore_errors: true

    # Verificar que rkhunter esté instalado
    - name: Ensure rkhunter is installed
      ansible.builtin.dnf:
        name: rkhunter
        state: present
      register: rkhunter_install_result
      ignore_errors: true

    # Evaluar compliance del servidor y recopilar detalles
    - name: Collect compliance results
      ansible.builtin.set_fact:
        compliance_status:
          hostname: "{{ inventory_hostname }}"
          firewall_installed: "{{ not firewall_install_result is failed }}"
          firewall_active: "{{ not firewall_status_result is failed }}"
          rkhunter_installed: "{{ not rkhunter_install_result is failed }}"
        server_compliance: >-
          {{
            not firewall_install_result is failed and
            not firewall_status_result is failed and
            not rkhunter_install_result is failed
          }}

    # Depurar estado de compliance por servidor
    - name: Debug server compliance
      ansible.builtin.debug:
        msg: >
          Server {{ inventory_hostname }} compliance details:
          - Firewall installed: {{ not firewall_install_result is failed }}
          - Firewall active: {{ not firewall_status_result is failed }}
          - rkhunter installed: {{ not rkhunter_install_result is failed }}
          - Compliant: {{ server_compliance }}

    # Actualizar lista de servidores no compliant
    - name: Update non-compliant servers list
      ansible.builtin.set_fact:
        non_compliant_servers: "{{ non_compliant_servers + [compliance_status] }}"
      when: not server_compliance
      run_once: true
      delegate_to: localhost

    # Depurar lista de servidores no compliant (opcional)
    - name: Debug non-compliant servers list
      ansible.builtin.debug:
        var: non_compliant_servers
      run_once: true
      delegate_to: localhost

    # Fallar el playbook si hay servidores no compliant
    - name: Fail the playbook if there are non-compliant servers
      ansible.builtin.fail:
        msg: >
          Compliance check failed. Non-compliant servers:
          {{ non_compliant_servers | to_nice_json }}
      when: non_compliant_servers | length > 0
      run_once: true
      delegate_to: localhost
