---
- name: Compliance Check for Linux Servers
  hosts: all
  gather_facts: true

  tasks:
    # Verificar que el firewall esté instalado
    - name: Ensure firewall is installed
      ansible.builtin.dnf:
        name: firewalld
        state: present
      register: firewall_install_result
      ignore_errors: true

    # Verificar que el firewall esté activo
    - name: Ensure firewall is active
      ansible.builtin.systemd:
        name: firewalld
        state: started
        enabled: true
      register: firewall_status_result
      ignore_errors: true

    # Verificar que rkhunter esté instalado
    - name: Ensure rkhunter is installed
      ansible.builtin.dnf:
        name: rkhunter
        state: present
      register: rkhunter_install_result
      ignore_errors: true

    # Evaluar compliance del servidor y recopilar detalles
    - name: Collect compliance results
      ansible.builtin.set_fact:
        server_compliance: >-
          {{
            not firewall_install_result is failed and
            not firewall_status_result is failed and
            not rkhunter_install_result is failed
          }}
        compliance_status:
          hostname: "{{ inventory_hostname }}"
          firewall_installed: "{{ not firewall_install_result is failed }}"
          firewall_active: "{{ not firewall_status_result is failed }}"
          rkhunter_installed: "{{ not rkhunter_install_result is failed }}"

    # Enviar los servidores no compliant a la lista global
    - name: Update non-compliant servers globally
      ansible.builtin.set_stats:
        data:
          non_compliant_servers_global: >-
            {{
              (non_compliant_servers_global | default([])) + [compliance_status]
            }}
      when: not server_compliance

    # Depurar lista de servidores no compliant
    - name: Debug non-compliant servers list
      ansible.builtin.debug:
        var: non_compliant_servers_global
      run_once: true
      delegate_to: localhost

    # Fallar el playbook si hay servidores no compliant
    - name: Fail the playbook if there are non-compliant servers
      ansible.builtin.fail:
        msg: >
          Compliance check failed. Non-compliant servers:
          {{ non_compliant_servers_global | to_nice_json }}
      when: non_compliant_servers_global is defined and non_compliant_servers_global | length > 0
      run_once: true
      delegate_to: localhost
