---
- name: Simplified Compliance Check for Linux Servers
  hosts: all
  gather_facts: true
  tasks:
    # Inicializar la lista de servidores no compliant en localhost
    - name: Initialize non-compliant servers list
      ansible.builtin.set_fact:
        non_compliant_servers: []
      delegate_to: localhost
      run_once: true

    # Verificar que el firewall esté instalado
    - name: Ensure firewall is installed
      ansible.builtin.dnf:
        name: firewalld
        state: present
      register: firewall_install_result

    # Verificar que el firewall esté activo
    - name: Ensure firewall is active
      ansible.builtin.systemd:
        name: firewalld
        state: started
        enabled: true
      register: firewall_status_result

    # Evaluar si el servidor es compliant
    - name: Check server compliance
      ansible.builtin.set_fact:
        server_compliance: >-
          {{
            firewall_install_result is succeeded and
            firewall_status_result is succeeded
          }}

    # Actualizar lista de servidores no compliant en localhost
    - name: Update list of non-compliant servers
      ansible.builtin.set_fact:
        non_compliant_servers: >-
          {{
            (non_compliant_servers | default([])) + [
              {
                "hostname": inventory_hostname,
                "firewall_installed": firewall_install_result is succeeded,
                "firewall_active": firewall_status_result is succeeded
              }
            ]
          }}
      when: not server_compliance
      delegate_to: localhost

    # Depurar la lista de servidores no compliant (opcional)
    - name: Debug non-compliant servers
      ansible.builtin.debug:
        var: non_compliant_servers
      delegate_to: localhost
      run_once: true

    # Marcar el playbook como fallido si hay problemas de compliance
    - name: Fail the playbook if there are non-compliant servers
      ansible.builtin.fail:
        msg: >
          Compliance check failed. The following servers are non-compliant:
          {{ non_compliant_servers | map(attribute='hostname') | join(', ') }}
      when: non_compliant_servers is defined and non_compliant_servers | length > 0
      delegate_to: localhost
      run_once: true
