---
- name: Compliance Check for Linux Servers
  hosts: all
  gather_facts: true
  tasks:
    # Verificar que el firewall esté instalado
    - name: Ensure firewall is installed
      ansible.builtin.dnf:
        name: firewalld
        state: present
      register: firewall_install_result

    # Verificar que el firewall esté activo
    - name: Ensure firewall is active
      ansible.builtin.systemd:
        name: firewalld
        state: started
        enabled: true
      register: firewall_status_result

    - name: Enable EPEL repository
      ansible.builtin.dnf:
        name: epel-release
        state: present

    # Verificar que el antivirus (chkrootkit) esté instalado
    - name: Ensure chkrootkit is installed
      ansible.builtin.dnf:
        name: chkrootkit
        state: present
      register: antivirus_install_result

    # Verificar que el antivirus esté funcionando correctamente
    - name: Run chkrootkit scan
      ansible.builtin.command:
        cmd: chkrootkit
      register: antivirus_scan_result
      changed_when: false
      failed_when: antivirus_scan_result.rc not in [0, 1]

    # Evaluar compliance del servidor
    - name: Check compliance for the server
      ansible.builtin.fail:
        msg: >
          Server {{ inventory_hostname }} is not compliant:
          - Firewall installed: {{ firewall_install_result is succeeded }}
          - Firewall active: {{ firewall_status_result is succeeded }}
          - Antivirus installed: {{ antivirus_install_result is succeeded }}
          - Antivirus scan successful: {{ antivirus_scan_result.rc in [0, 1] }}
      when: >
        not (
          firewall_install_result is succeeded and
          firewall_status_result is succeeded and
          antivirus_install_result is succeeded and
          antivirus_scan_result.rc in [0, 1]
        )

    # Depurar estado de compliance (opcional)
    - name: Debug server compliance status
      ansible.builtin.debug:
        msg: >
          Server {{ inventory_hostname }} is compliant:
          - Firewall installed: {{ firewall_install_result is succeeded }}
          - Firewall active: {{ firewall_status_result is succeeded }}
          - Antivirus installed: {{ antivirus_install_result is succeeded }}
          - Antivirus scan successful: {{ antivirus_scan_result.rc in [0, 1] }}
      when: >
        firewall_install_result is succeeded and
        firewall_status_result is succeeded and
        antivirus_install_result is succeeded and
        antivirus_scan_result.rc in [0, 1]
