---
- name: Compliance Check for Linux Servers
  hosts: all
  gather_facts: true
  vars:
    non_compliant_servers: []

  tasks:
    # Verificar que el firewall esté instalado
    - name: Ensure firewall is installed
      ansible.builtin.dnf:
        name: firewalld
        state: present
      register: firewall_install_result
      ignore_errors: true

    # Verificar que el firewall esté activo
    - name: Ensure firewall is active
      ansible.builtin.systemd:
        name: firewalld
        state: started
        enabled: true
      register: firewall_status_result
      ignore_errors: true

    # Verificar que rkhunter esté instalado
    - name: Ensure rkhunter is installed
      ansible.builtin.dnf:
        name: rkhunter
        state: present
      register: rkhunter_install_result
      ignore_errors: true

    # Evaluar compliance del servidor
    - name: Collect compliance results
      ansible.builtin.set_fact:
        server_compliance:
          hostname: "{{ inventory_hostname }}"
          firewall_installed: "{{ not firewall_install_result is failed }}"
          firewall_active: "{{ not firewall_status_result is failed }}"
          rkhunter_installed: "{{ not rkhunter_install_result is failed }}"
        server_is_compliant: >-
          {{
            not firewall_install_result is failed and
            not firewall_status_result is failed and
            not rkhunter_install_result is failed
          }}

    # Agregar servidores no compliant a una lista temporal
    - name: Add non-compliant server to temporary list
      ansible.builtin.set_fact:
        non_compliant_servers: "{{ non_compliant_servers + [server_compliance] }}"
      when: not server_is_compliant

    # Consolidar lista global de servidores no compliant
    - name: Consolidate non-compliant servers globally
      ansible.builtin.set_stats:
        data:
          non_compliant_servers_global: "{{ non_compliant_servers }}"
      run_once: true

    # Depurar la lista consolidada
    - name: Debug consolidated non-compliant servers list
      ansible.builtin.debug:
        var: non_compliant_servers_global
      run_once: true

    # Fallar el playbook si hay servidores no compliant
    - name: Fail the playbook if there are non-compliant servers
      ansible.builtin.fail:
        msg: >
          Compliance check failed. Non-compliant servers:
          {{ non_compliant_servers_global | to_nice_json }}
      when: non_compliant_servers_global is defined and non_compliant_servers_global | length > 0
      run_once: true
