- name: Clonar una VM desde una plantilla en Proxmox
  hosts: localhost
  tasks:
    - name: Clonar VM desde plantilla
      community.general.proxmox_kvm:
        api_host: "192.168.0.10"       # Direcci칩n del servidor Proxmox
        api_user: "root@pam"           # Usuario con permisos
        api_password: "206xs75"    # Contrase침a del usuario
        validate_certs: false          # Validaci칩n de certificados SSL
        node: "proxmox2"               # Nodo donde reside la plantilla
        clone: Almalinux
        vmid: 106                     # ID de la plantilla existente
        newid: 200                     # ID de la nueva VM
        storage: "nvme"                # Almacenamiento para la VM
        state: present                 # Crear la VM
        full: true                     # Clonaci칩n completa
      register: result      

    - name: Mostrar resultados
      debug:
        var: result