- name: Clonar una VM desde una plantilla en Proxmox
  hosts: localhost
  tasks:
    - name: Clonar VM desde plantilla
      community.general.proxmox_kvm:
        api_host: "{{ lookup('env', 'PROXMOX_API_HOST') }}"
        api_user: "{{ lookup('env', 'PROXMOX_API_USER') }}"
        api_password: "{{ lookup('env', 'PROXMOX_API_PASSWORD') }}"
        validate_certs: false          
        node: "proxmox2"               # Nodo donde reside la plantilla
        clone: Almalinux               # Nombre de la plantilla a clonar
        vmid: 106                      # ID de la plantilla existente        
        name: newdeploy                # Nombre
        storage: "nvme"                # Almacenamiento para la VM        
        full: true                     # Clonación completa
        timeout: 240                   # Tiempo de espera
      register: clone_result      

    - name: Obtener el VMID del resultado
      set_fact:
        new_vmid: "{{ clone_result.vmid }}"

    - name: Cambiar el nombre de la VM al finalizar
      community.general.proxmox_kvm:
        community.general.proxmox_kvm:
        api_host: "{{ lookup('env', 'PROXMOX_API_HOST') }}"
        api_user: "{{ lookup('env', 'PROXMOX_API_USER') }}"
        api_password: "{{ lookup('env', 'PROXMOX_API_PASSWORD') }}"
        validate_certs: false
        node: "proxmox2"
        vmid: "{{ new_vmid }}"     # ID de la VM clonada
        name: "server{{ new_vmid }}" # Nombre final basado en VMID
        update: true              # Actualizar la configuración
      register: update_result

    - name: Mostrar resultados del clon y renombrado
      debug:
        msg:
          - "Clonación realizada con VMID: {{ new_vmid }}"
          - "VM renombrada a: server{{ new_vmid }}"