- name: Probar conexión a Proxmox
  hosts: localhost
  tasks:
    - name: Listar nodos en Proxmox
      community.general.proxmox:
        api_host: "{{ lookup('env', 'PROXMOX_API_HOST') }}"
        api_user: "{{ lookup('env', 'PROXMOX_API_USER') }}"
        api_password: "{{ lookup('env', 'PROXMOX_API_PASSWORD') }}"
        validate_certs: "{{ validate_certs }}"
        endpoint: "/nodes"
        method: GET
