- name: Clonar una VM desde una plantilla en Proxmox al siguiente VMID disponible
  hosts: localhost
  tasks:
    - name: Obtener lista de todas las VMs y contenedores
      community.general.proxmox_kvm:
        api_host: "{{ lookup('env', 'PROXMOX_API_HOST') }}"
        api_user: "{{ lookup('env', 'PROXMOX_API_USER') }}"
        api_password: "{{ lookup('env', 'PROXMOX_API_PASSWORD') }}"
        validate_certs: false
        state: info
      register: vm_list

    - name: Calcular siguiente VMID disponible
      set_fact:
        next_vmid: >-
          {{ (vm_list.instances | map(attribute='vmid') | map('int') | list | max) + 1 }}

    - name: Clonar VM desde plantilla
      community.general.proxmox_kvm:
        api_host: "{{ lookup('env', 'PROXMOX_API_HOST') }}"
        api_user: "{{ lookup('env', 'PROXMOX_API_USER') }}"
        api_password: "{{ lookup('env', 'PROXMOX_API_PASSWORD') }}"
        validate_certs: false
        node: "proxmox2"
        clone: Almalinux
        vmid: 106
        newid: "{{ next_vmid }}"
        name: "Almalinuxdeployed-{{ next_vmid }}"
        storage: "nvme"
        state: present
        full: true
        timeout: 240
      register: result

    - name: Mostrar resultados
      debug:
        var: result
