- name: Clonar una VM desde una plantilla en Proxmox y encenderla
  hosts: localhost
  tasks:
    - name: Clonar VM desde plantilla
      community.general.proxmox_kvm:
        api_host: "{{ lookup('env', 'PROXMOX_API_HOST') }}"
        api_user: "{{ lookup('env', 'PROXMOX_API_USER') }}"
        api_password: "{{ lookup('env', 'PROXMOX_API_PASSWORD') }}"
        validate_certs: false
        node: "proxmox2"               # Nodo donde reside la plantilla
        clone: Almalinux               # Nombre de la plantilla a clonar
        vmid: 106                      # ID de la plantilla existente        
        name: newdeploy                # Nombre inicial
        storage: "nvme"                # Almacenamiento para la VM        
        full: true                     # Clonación completa
        timeout: 240                   # Tiempo de espera
      register: clone_result      

    - name: Obtener el VMID del resultado
      set_fact:
        new_vmid: "{{ clone_result.vmid }}"

    - name: Cambiar el nombre de la VM al finalizar
      community.general.proxmox_kvm:
        api_host: "{{ lookup('env', 'PROXMOX_API_HOST') }}"
        api_user: "{{ lookup('env', 'PROXMOX_API_USER') }}"
        api_password: "{{ lookup('env', 'PROXMOX_API_PASSWORD') }}"
        validate_certs: false
        node: "proxmox2"
        vmid: "{{ new_vmid }}"         # ID de la VM clonada
        name: "server{{ new_vmid }}"   # Nombre final basado en VMID
        update: true                   # Actualizar la configuración
        state: present
      register: update_result

    - name: Encender la máquina virtual
      community.general.proxmox_kvm:
        api_host: "{{ lookup('env', 'PROXMOX_API_HOST') }}"
        api_user: "{{ lookup('env', 'PROXMOX_API_USER') }}"
        api_password: "{{ lookup('env', 'PROXMOX_API_PASSWORD') }}"
        validate_certs: false
        node: "proxmox2"
        vmid: "{{ new_vmid }}"         # ID de la VM clonada
        state: started                 # Encender la máquina

    - name: Esperar 1 minuto a que la VM arranque
      pause:
        minutes: 1

    - name: Obtener la información de red de la máquina
      community.general.proxmox_vm_info:
        api_host: "{{ lookup('env', 'PROXMOX_API_HOST') }}"
        api_user: "{{ lookup('env', 'PROXMOX_API_USER') }}"
        api_password: "{{ lookup('env', 'PROXMOX_API_PASSWORD') }}"
        validate_certs: false
        node: "proxmox2"
        vmid: "{{ new_vmid }}"
        state: current
      register: vm_info

    - name: Establecer la IP de la máquina clonada
      set_fact:
        server_ip: "{{ vm_info.instance.network.interfaces[0].ip_addresses[0] }}"

    - name: Mostrar la información obtenida
      debug:
        var: vm_info

    - name: Cambiar el nombre de la máquina a nivel de SO
      ansible.builtin.shell: |
        hostnamectl set-hostname server{{ new_vmid }}
      vars:
        ansible_user: "{{ lookup('env', 'USERNAME') }}"
        ansible_ssh_pass: "{{ lookup('env', 'PASSWORD') }}"
      delegate_to: "{{ server_ip }}"
      become: yes

    - name: Mostrar resultados del clon, renombrado y encendido
      debug:
        msg:
          - "Clonación realizada con VMID: {{ new_vmid }}"
          - "VM renombrada a nivel Proxmox: server{{ new_vmid }}"
          - "Nombre del SO cambiado a: server{{ new_vmid }}"
          - "Dirección IP de la máquina: {{ server_ip }}"