- name: Desplegar VM en Proxmox desde plantilla
  hosts: localhost
  tasks:
    - name: Crear VM en Proxmox desde plantilla
      community.general.proxmox:
        api_host: "{{ lookup('env', 'PROXMOX_API_HOST') }}"
        api_user: "{{ lookup('env', 'PROXMOX_API_USER') }}"
        api_password: "{{ lookup('env', 'PROXMOX_API_PASSWORD') }}"
        validate_certs: "{{ lookup('env', 'PROXMOX_VALIDATE_CERTS') }}"
        node: "proxmox2"            # Nodo donde se encuentra la plantilla
        clone: 106   # Nombre o ID de la plantilla
        vmid: 200                   # ID único para la nueva VM
        name: "Almalinuxdeployed"         # Nombre de la nueva VM
        target: "proxmox2"          # Nodo donde se creará la nueva VM
        full: true                  # Clon completo (true) o vinculado (false)
        pool: "Ansibledeployed"             # (Opcional) Pool donde se asignará la VM
        storage: "nvme"        # Almacenamiento donde se ubicará el disco
        cores: 2                    # Número de núcleos de CPU
        memory: 2048                # Memoria RAM en MB
        state: present
      register: result

    - name: Mostrar resultados
      debug:
        var: result