---
- name: Registrar incidente en Servicenow para actualización fallida en Linux
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Depurar servidores no compliance
      ansible.builtin.debug:
        var: non_compliant_servers_global

    - name: Formatear servidores fallidos en JSON legible
      ansible.builtin.set_fact:
        formatted_non_compliant_servers: "{{ non_compliant_servers_global | to_nice_json }}"

    - name: Registrar el incidente en Servicenow
      servicenow.itsm.incident:
        instance:
          host: https://dev262465.service-now.com
          username: "{{ ansible_user }}"
          password: "{{ ansible_password }}"
        state: new
        caller: AAP25_API
        short_description: "Errores en la verificación automática de compliance"
        description: >
          Existen servidores no compliance en la verificación automática:
          {{ formatted_non_compliant_servers }}
      register: snow_incident

    - name: Verificar la respuesta de Servicenow
      ansible.builtin.debug:
        var: snow_incident
